apiVersion: v1
kind: Pod
metadata:
  name: kod-explorer
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: phpdata
      - mountPath: /etc/nginx/conf.d
        name: nginxconf  
    resources: {}
  - image: php:5.6-fpm
    imagePullPolicy: IfNotPresent
    name: php
    resources: {}  
    ports:
      - containerPort: 9000
    volumeMounts:
      - mountPath: /var/www/html
        name: phpdata
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: phpdata
      hostPath:
        path: /Users/czm/test/nginx-exporter/http
    - name: nginxconf
      hostPath:
        path: /Users/czm/test/conf   
