apiVersion: apps/v1
kind: Deployment
metadata:
  name: kod-explorer
  labels:
    app: kod-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kod-explorer
  template:
    metadata:
      labels:
        app: kod-explorer
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: phpdata
          - mountPath: /etc/nginx/conf.d
            name: nginxconf  
        resources: {}
      - image: allenczm/kod:v1
        imagePullPolicy: IfNotPresent
        name: php
        resources: {}  
        env:
        - name: PASSWORD
          value: "123456"
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: /var/www/html
            name: phpdata
      dnsPolicy: ClusterFirst
      volumes:
        - name: phpdata
          hostPath:
            path: /Users/czm/test/nginx-exporter/http
        - name: nginxconf
          hostPath:
            path: /Users/czm/test/conf  
   
